# Generated by Django 4.2.1 on 2023-05-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("0", "未處理"),
                    ("1", "文字稿生成完成"),
                    ("2", "Deepl翻譯完成"),
                    ("3", "Play.ht語音生成完成"),
                    ("4", "Status 4"),
                    (None, "N/A"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="voice_selection",
            field=models.CharField(
                choices=[
                    ("ko-KR-Standard-A", "ko-KR-Standard-A"),
                    ("larry", "larry"),
                    ("zh-TW-YunJheNeural", "zh-TW-YunJheNeural"),
                ],
                max_length=255,
            ),
        ),
    ]
