# Generated by Django 4.2.1 on 2023-05-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="edit_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="title",
            field=models.CharField(default="default title", max_length=255),
            preserve_default=False,
        ),
    ]
