# Generated by Django 4.2.6 on 2023-10-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="needBgmusic",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="needModify",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("0", "未處理"),
                    ("1", "文字稿生成中"),
                    ("2", "Deepl翻譯中"),
                    ("3", "Play.ht語音生成中"),
                    ("4", "語音合成中"),
                    ("5", "背景音樂合成中"),
                    ("6", "影片合成中"),
                    ("7", "任務停止，等待用戶繼續"),
                    ("8", "任務完成"),
                    ("-1", "任務失敗"),
                    ("-2", "任務取消"),
                    ("None", "N/A"),
                ],
                default="0",
                max_length=50,
            ),
        ),
    ]
