# Generated by Django 4.2.1 on 2023-05-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_task_edit_mode_task_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="url",
        ),
        migrations.AddField(
            model_name="task",
            name="file",
            field=models.FileField(null=True, upload_to="uploads/"),
            preserve_default=False,
        ),
    ]
