# Generated by Django 3.2.19 on 2023-06-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_edit_mode_task_needmodify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('0', '未處理'), ('1', '文字稿生成完成'), ('2', 'Deepl翻譯完成'), ('3', 'Play.ht語音生成完成'), ('4', '任務完成'), ('-1', '任務失敗'), ('-2', '任務取消'), ('None', 'N/A')], default='0', max_length=50),
        ),
    ]
