# Generated by Django 4.2.1 on 2023-06-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_task_url_task_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="file",
        ),
        migrations.AddField(
            model_name="task",
            name="fileLocation",
            field=models.CharField(default="video-temp/CmwSf7rI2II.m4a", max_length=50),
        ),
    ]
