# Generated by Django 3.2.19 on 2023-06-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('0', '未處理'), ('1', '文字稿生成中'), ('2', 'Deepl翻譯中'), ('3', 'Play.ht語音生成中'), ('4', '語音合成中'), ('5', '影片合成中'), ('6', '任務完成'), ('-1', '任務失敗'), ('-2', '任務取消'), ('None', 'N/A')], default='0', max_length=50),
        ),
    ]
