# Generated by Django 3.2.19 on 2023-07-09 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0008_auto_20230709_1721'),
        ('core', '0005_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='voice_selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='audio.play_ht_voices', to_field='voice'),
        ),
    ]
