# Generated by Django 4.2.1 on 2023-07-22 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0004_remove_deepl_taskid'),
        ('audio', '0009_remove_play_ht_taskid'),
        ('core', '0007_task_transcript_task_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deepl',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='translator.deepl'),
        ),
        migrations.AddField(
            model_name='task',
            name='playht',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='audio.play_ht'),
        ),
    ]
