# Generated by Django 4.2.1 on 2023-05-15 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Play_ht",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("length_ratio", models.FloatField()),
                ("origin_audio_url", models.URLField()),
                ("changed_audi_url", models.URLField()),
                ("status", models.BooleanField(default=False)),
                (
                    "taskID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.task"
                    ),
                ),
            ],
        ),
    ]
