# Generated by Django 4.2.1 on 2023-05-18 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audio", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="play_ht",
            old_name="changed_audi_url",
            new_name="changed_audio_url",
        ),
    ]
