# Generated by Django 3.2.19 on 2023-06-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Play_ht_voices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('voice', models.CharField(max_length=10)),
                ('voice_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
