# Generated by Django 4.2.6 on 2023-10-20 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="play_ht",
            name="length_ratio",
        ),
    ]
