# Generated by Django 3.2.19 on 2023-06-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_play_ht_voices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play_ht_voices',
            name='language',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='play_ht_voices',
            name='voice',
            field=models.CharField(max_length=30),
        ),
    ]
