# Generated by Django 3.2.19 on 2023-06-30 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_task_status'),
        ('audio', '0003_auto_20230625_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='play_ht',
            name='transcriptionId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Play_ht_webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcriptionId', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('taskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.task')),
            ],
        ),
    ]
