# Generated by Django 3.2.19 on 2023-07-07 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0005_auto_20230630_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play_ht_voices',
            name='language',
        ),
        migrations.CreateModel(
            name='LanguageMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_language', models.CharField(max_length=30, unique=True)),
                ('mapped_language', models.CharField(max_length=30)),
            ],
            options={
                'unique_together': {('original_language', 'mapped_language')},
            },
        ),
        migrations.AddField(
            model_name='play_ht_voices',
            name='language_mapping',
            field=models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.CASCADE, to='audio.languagemapping', to_field='original_language'),
        ),
    ]
