# Generated by Django 3.2.19 on 2023-07-07 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0006_auto_20230707_1740'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='languagemapping',
            unique_together=set(),
        ),
    ]
