# Generated by Django 3.2.19 on 2023-07-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0007_alter_languagemapping_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play_ht',
            name='origin_audio_url',
        ),
        migrations.AlterField(
            model_name='play_ht_voices',
            name='voice',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
