# Generated by Django 4.2.1 on 2023-07-22 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0008_auto_20230709_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play_ht',
            name='taskID',
        ),
    ]
