# Generated by Django 4.2.1 on 2023-05-15 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deepl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translated_text", models.TextField()),
                ("status", models.BooleanField(default=False)),
                (
                    "taskID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.task"
                    ),
                ),
            ],
        ),
    ]
