# Generated by Django 4.2.1 on 2023-07-22 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0002_transformedtext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransformedText',
        ),
    ]
