# Generated by Django 4.2.1 on 2023-07-22 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0003_delete_transformedtext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deepl',
            name='taskID',
        ),
    ]
