# Generated by Django 4.2.6 on 2023-10-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transcript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transcript", models.JSONField(blank=True, null=True)),
                ("modified_transcript", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "length",
                    models.DecimalField(decimal_places=2, default=10, max_digits=6),
                ),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
                ("speaker_counts", models.IntegerField(default=1)),
                ("status", models.BooleanField(default=False)),
            ],
        ),
    ]
