# Generated by Django 3.2.19 on 2023-07-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
