# Generated by Django 4.2 on 2023-04-26 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="video", name="id",),
        migrations.AlterField(
            model_name="transcript",
            name="video",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="video.video",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="url",
            field=models.URLField(primary_key=True, serialize=False),
        ),
    ]
