name: Test
on:
  push:
    branches:
      - main
      - video_trans
jobs:
  test-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and install FFmpeg
        run: |
          wget https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz
          tar xf ffmpeg-master-latest-linux64-gpl.tar.xz -C /opt
          
      - name: Set environment variable for ffmpeg
        run: echo "export PATH=$PATH:/opt/ffmpeg-master-latest-linux64-gpl/bin" >> $GITHUB_ENV

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: FFmpeg
        run: |
          pip3 uninstall ffmpeg
          pip3 uninstall ffmpeg-python
          pip uninstall ffmpeg
          pip uninstall ffmpeg-python
          brew uninstall ffmpeg
          pip3 install ffmpeg-python
          brew install ffmpeg

      - name: Run tests
        run: python manage.py test
  test-video_trans:
    if: github.ref == 'refs/heads/video_trans'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python manage.py test video.tests
  deploy:
    needs: [test-main, test-video_trans]
    if: github.ref == 'refs/heads/main' && needs.test-main.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Install Flyctl CLI
        uses: superfly/flyctl-actions@v0.3.1
        with:
          version: latest
      - name: Deploy to Fly.io
        run: |
          flyctl deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  