name: Test
on:
  push:
    branches:
      - main
      - video_trans
jobs:
  test-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download FFmpeg source code
        run: git clone https://git.ffmpeg.org/ffmpeg.git
      - name: Build and install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git-core checkinstall yasm texi2html \
              libvorbis-dev libx11-dev libvpx-dev libx264-dev libtheora-dev \
              libmp3lame-dev libopus-dev libx265-dev libass-dev libwebp-dev
          cd ffmpeg
          ./configure --enable-shared --disable-static
          make -j$(nproc)
          sudo make install
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python manage.py test
  test-video_trans:
    if: github.ref == 'refs/heads/video_trans'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python manage.py test video.tests

  