name: Test
on:
  push:
    branches:
      - main
      - video_trans
jobs:
  test-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download FFmpeg source code
        run: git clone https://git.ffmpeg.org/ffmpeg.git

      - name: Build and install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install FFmpeg
          
      - name: Set environment variable for ffmpeg
        run: echo "export PATH=$PATH:/usr/local/bin/ffmpeg" >> $GITHUB_ENV

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python manage.py test
  test-video_trans:
    if: github.ref == 'refs/heads/video_trans'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python manage.py test video.tests
  deploy:
    needs: [test-main, test-video_trans]
    if: github.ref == 'refs/heads/main' && needs.test-main.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Install Flyctl CLI
        uses: superfly/flyctl-actions@v0.3.1
        with:
          version: latest
      - name: Deploy to Fly.io
        run: |
          flyctl deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  